# https://docs.github.com/cn/repositories/releasing-projects-on-github/automatically-generated-release-notes#configuration-options
changelog:
  exclude:
    labels:
      - meta
  categories:
    - title: Exciting New Features 🎉
      labels:
        - enhancement
        - new
    - title: Bugfixes 🐛
      labels:
        - bug
    - title: Other Changes ✨
      labels:
        - "*"