name: 每日Issues

on:
  schedule:
    - cron: "25 */12 * * *"

jobs:
  issue-label-stale:
    name: Label stale issues
    runs-on: ubuntu-latest
    steps:
      - uses: actions-cool/issues-helper@v3
        with:
          actions: check-inactive
          token: ${{ secrets.GITHUB_TOKEN }}
          inactive-day: 3
          inactive-label: stale
          exclude-labels: bug, documentation, enhancement, stale
          body: |
            This issue is marked as `stale` because it has not had recent activity. Issues marked with `stale` will be closed if they have no activity within 3 days.
  
  issue-close-stale:
    name: Close stale issues
    runs-on: ubuntu-latest
    steps:
      - uses: actions-cool/issues-helper@v3
        with:
          actions: close-issues
          token: ${{ secrets.GITHUB_TOKEN }}
          labels: stale
          inactive-day: 3
  
  issue-invalid:
    name: Close invalid issue
    if: github.event.label.name == 'invalid'
    runs-on: ubuntu-latest
    steps:
      - uses: actions-cool/issues-helper@v3
        with:
          actions: close-issue, create-comment
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            Hello @${{ github.event.issue.user.login }}. This issue is marked as `invalid` and closed. Please make sure you are reporting an issue and following the issue template.
